import { Injectable } from '@angular/core';
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import { environment } from '../../environments/environment';

@Injectable({ providedIn: 'root' })
export class GoogleSheetsService {
    /**
     * Retrieve rows from the configured Google Sheet.
     * - This runs server-side only (service account private key must not be exposed to the browser).
     * - Returns an array of objects keyed by header name with an additional `_rawData` array per row.
     */
    async getData(sheetIndex = 0, sheetTitle?: string): Promise<Record<string, any>[]> {
        // In the browser, call the server API endpoint instead of using service account creds
        if (typeof window !== 'undefined') {
            const params = new URLSearchParams();
            if (sheetTitle) params.set('title', sheetTitle);
            else params.set('index', String(sheetIndex));
            const res = await fetch(`/api/sheet?${params.toString()}`, { method: 'GET' });
            if (!res.ok) {
                console.warn('GoogleSheetsService.getData: API request failed', await res.text());
                return [];
            }
            const payload = await res.json();
            return payload && payload.data ? payload.data : [];
        }

        try {
            const sheetId = environment.SHEET_ID;
            if (!sheetId) {
                console.warn('GoogleSheetsService.getData: no SHEET_ID configured.');
                return [];
            }

            const serviceAccountAuth = new JWT({
                // env var values here are copied from service account credentials generated by google
                // see "Authentication" section in docs for more info
                email: environment['GOOGLE_SERVICE_ACCOUNT_EMAIL'],
                key: environment['GOOGLE_PRIVATE_KEY'],
                scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly'],
            });

            const doc = new GoogleSpreadsheet(sheetId, serviceAccountAuth);

            await doc.loadInfo();

            // Choose sheet: prefer title if provided, otherwise index
            let sheet: any | undefined;
            if (sheetTitle) sheet = (doc as any).sheetsByTitle && (doc as any).sheetsByTitle[sheetTitle];
            if (!sheet && typeof sheetIndex === 'number') sheet = doc.sheetsByIndex[sheetIndex];
            if (!sheet) sheet = doc.sheetsByIndex[0];
            if (!sheet) return [];
            console.log('GoogleSheetsService: using sheet', sheet.title);

            // Determine header row (1-based). Default to env SHEET_HEADER_ROW or 1.
            const headerRow = Number(environment.SHEET_HEADER_ROW ?? 1);

            // If headers are not on the first row, fetch them via the Sheets API and set `sheet.headerValues`
            let headersAvailable = false;
            try { headersAvailable = Array.isArray(sheet.headerValues) && sheet.headerValues.length > 0; } catch (e) { headersAvailable = false; }

            if (headerRow > 1 || !headersAvailable) {
                try {
                    const jwt = new JWT({
                        email: environment.GOOGLE_SERVICE_ACCOUNT_EMAIL,
                        key: (environment.GOOGLE_PRIVATE_KEY ?? '').replace(/\\n/g, '\\n').replace(/\\n/g, '\n'),
                        scopes: ['https://www.googleapis.com/auth/spreadsheets'],
                    });
                    // authorize to populate credentials
                    await jwt.authorize();
                    let accessToken: string | undefined = (jwt as any).credentials?.access_token;
                    if (!accessToken) {
                        const atRes = await (jwt as any).getAccessToken();
                        accessToken = typeof atRes === 'string' ? atRes : atRes?.token;
                    }
                    if (accessToken) {
                        // sheet.title may contain spaces; wrap in single quotes per A1 notation
                        const range = `'${sheet.title}'!${headerRow}:${headerRow}`;
                        const url = `https://sheets.googleapis.com/v4/spreadsheets/${sheetId}/values/${encodeURIComponent(range)}?majorDimension=ROWS`;
                        const res = await fetch(url, { headers: { Authorization: `Bearer ${accessToken}` } });
                        if (res.ok) {
                            const json = await res.json();
                            if (Array.isArray(json.values) && json.values.length > 0) {
                                sheet.headerValues = json.values[0].map((v: any) => String(v));
                                console.log('GoogleSheetsService: header values set from row', headerRow, sheet.headerValues);
                            } else {
                                console.warn('GoogleSheetsService: no header values returned for row', headerRow);
                            }
                        } else {
                            console.warn('GoogleSheetsService: failed to fetch header row', await res.text());
                        }
                    }
                } catch (err) {
                    console.warn('GoogleSheetsService: could not fetch header row via API', err);
                }
            }

            const rows = await sheet.getRows();
            const headers = sheet.headerValues || [];

            const data = rows.map((r: any) => {
                const obj: Record<string, any> = {};
                for (const h of headers) obj[h] = r[h];
                obj['_rawData'] = r._rawData;
                return obj;
            });

            return data;
        } catch (err) {
            console.error('GoogleSheetsService.getData error', err);
            return [];
        }
    }
}