import { Injectable } from '@angular/core';
import { Routes } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import { environment } from '../../environments/environment';

@Injectable()
export class GoogleSheetsService {
    public routes: Routes = [];

    async getData(): Promise<any> {
        const serviceAccountAuth = new JWT({
            // env var values here are copied from service account credentials generated by google
            // see "Authentication" section in docs for more info
            email: environment['GOOGLE_SERVICE_ACCOUNT_EMAIL'],
            key: environment['GOOGLE_PRIVATE_KEY'],
            scopes: ['https://www.googleapis.com/auth/spreadsheets'],
        });

        const doc = new GoogleSpreadsheet('<the sheet ID from the url>', serviceAccountAuth);

        await doc.loadInfo(); // loads document properties and worksheets
        console.log(doc.title);
        await doc.updateProperties({ title: 'renamed doc' });

        const sheet = doc.sheetsByIndex[0]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
        console.log(sheet.title);
        console.log(sheet.rowCount);
    }
}